### ISSUE TITLE
去掉点击时的选区和阴影

### ISSUE THREAD

**Issue by mqliutie** [mqliutie/wonderful-question#11]
```CSS
<style type="text/css">
div,a,img {
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    user-select:none;
}
</style>
```
